MonitoringSystem/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('devices/', include('websiteapp.urls'), name='list_devices'),
    path('api/', include('notification_system.urls'), name='api-main'),
    path('', RedirectView.as_view(pattern_name='websiteapp:integration', permanent=False))
]



from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notification_system/urls.py
from django.urls import path
from .views import DeviceView, UserCreate, LoginView


app_name = 'api'

urlpatterns = [
    path('report/<uuid:pk>/',  DeviceView.as_view(), name='report-api'),
    path("users/", UserCreate.as_view(), name="user_create"),
    path("login/", LoginView.as_view(), name="login"),
]

websiteapp/urls.py
from django.urls import path
from .views import ListDevices, CreateDevice, DetailDevice, Integration, Signup

app_name = 'websiteapp'

urlpatterns = [
    path('', ListDevices.as_view(), name='list_devices'),
    path('add-device/', CreateDevice.as_view(), name='add_device_form'),
    path('detail/<uuid:pk>/<slug:timestamp>', DetailDevice.as_view(), name='detail_device'),
    path('integrate', Integration.as_view(), name='integration'),
    path('signup/', Signup.as_view(), name="signup")
]

websiteapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import uuid

class Device(models.Model):
    title = models.CharField(
        max_length=255,
    )
    serial_number = models.CharField(
        max_length=255,
    )
    quantity = models.CharField(
        max_length=255,
    )
    owner = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True
    )
    dev_id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4, 
        help_text="Unique ID for this particular Device"
    )
    border_value = models.FloatField(
        max_length=100
    )

    def get_absolute_url(self):
        return reverse('websiteapp:detail_device', args=[str(self.dev_id), 'alltime'])

    def get_title(self):
        return self.title
    
    def get_serial_number(self):
        return self.serial_number

    def get_quantity(self):
        return self.quantity
    
    def get_uuid(self):
        return self.dev_id

    def get_border_value(self):
        return self.border_value
        
    def __str__(self):
        return ' '.join([self.title, self.serial_number, self.quantity])

class Measurement(models.Model):
    time = models.DateTimeField(
        null=True,
    )
    value = models.FloatField(
        max_length=100
    )
    device_id = models.ForeignKey(
        Device, 
        on_delete=models.CASCADE,
        to_field='dev_id',
        default=uuid.uuid4,
    )
    ip_feedback = models.GenericIPAddressField(
        null=True
    )

    def __str__(self):
        return ' '.join([str(self.value), str(self.time)])

websiteapp/forms.py
from django import forms
from .models import Device
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
    
class AddDeviceForm(forms.ModelForm):

    class Meta:
        model = Device
        fields = ['title', 'serial_number', 'quantity', 'border_value']    


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True, label='Email')
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")
    
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user

websiteapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse
from django.views.generic.edit import CreateView
from rest_framework.authtoken.models import Token
from .models import Device, Measurement
from django.shortcuts import render
from .forms import AddDeviceForm, UserCreationForm
import datetime
import json

class ListDevices(LoginRequiredMixin, ListView):
    template_name = 'list_devices.html'
    model = Device

    def get_queryset(self):
        return Device.objects.filter(owner=self.request.user).order_by('serial_number')

class CreateDevice(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = AddDeviceForm()
        context = {'form': form}
        return render(request, 'add_device.html', context)

    def post(self, request, *args, **kwargs):
        form = AddDeviceForm(data=request.POST)
        if form.is_valid():
            device = form.save(commit=False)
            device.owner = request.user
            device.save()
            return redirect('websiteapp:list_devices')
        return render(request, 'add_device.html', {'form': form})


class DetailDevice(LoginRequiredMixin, DetailView):
    template_name = 'device_detail.html'
    model = Device

    def define_timestamp(self):
        if 'timestamp' in self.kwargs.keys():
            timest = self.kwargs['timestamp'].lower()
            if timest == 'hour':
                return (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(hours=1), 'hour')
            if timest == 'day':
                return (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=1), 'day')
            if timest == 'week':
                return (datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(weeks=1), 'week')
        return (None, 'All the time')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user != Device.objects.get(dev_id=self.kwargs['pk']).owner:
            context['failed'] = True
            return context
        timestamp = self.define_timestamp()
        if timestamp[0] != None:
            queryset = Measurement.objects.filter(device_id=self.kwargs['pk'], time__gt=timestamp[0]).values_list('time', 'value').order_by('time')
            context['timeperiod'] = timestamp[1]
        else:
            queryset = Measurement.objects.filter(device_id=self.kwargs['pk']).values_list('time', 'value').order_by('time')
            context['timeperiod'] = timestamp[1]
        context['times'] = json.dumps([obj[0] for obj in queryset], default=str)
        context['values'] = json.dumps([obj[1] for obj in queryset])
        context['device'] = Device.objects.filter(dev_id=self.kwargs['pk']).get()
        context['total_measures'] = len(queryset)
        return context
 

class Integration(View):
    template_name = 'integration.html'

    def get(self, request):
        data_dict = {'token' : "None"}
        if request.user.is_authenticated:
            token = token = Token.objects.get_or_create(user=request.user)
            data_dict['token'] = token[0]
        return render(request, 'integration.html', context=data_dict)
from django.urls import reverse_lazy

success_url = reverse_lazy('login')

class Signup(CreateView):
    form_class = UserCreationForm
    template_name = 'signup.html'
    success_url = reverse_lazy('login')

websiteapp/templates/add_device.html
{% extends "base_generic.html" %}

{% block main_page_title %}
    Adding a New Device
{% endblock %}

{% block content %}
    <form method="POST" class="form-horizontal post-form">
        <form action="/thankyou/" method="post">
            {% csrf_token %}
            <table>
            {{form.as_table}}
        
         </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

websiteapp/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    
    {% block title %}<title>Monitoring System</title>{% endblock %}
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/row_menu.css' %}">
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="/devices">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline></svg>
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'websiteapp:list_devices' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
                  Devices
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'websiteapp:integration' %}">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-layers"><polygon points="12 2 2 7 12 12 22 7 12 2"></polygon><polyline points="2 17 12 22 22 17"></polyline><polyline points="2 12 12 17 22 12"></polyline></svg>
                  Integration
                </a>
              </li>
            </ul>
            {% block detail_monitoring %}
            {% endblock %}
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4"><div style="position: absolute; inset: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;" class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
            <h1 class="h2">
              {% block main_page_title %}
                Home
              {% endblock %}
            </h1>
            {% if user.is_authenticated %}
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-1">
                <button class="btn btn-sm btn-outline-secondary"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></button>
              </div>
              <div class="btn-group mr-1">
                <button class="btn btn-sm btn-outline-secondary">{{ user.get_username }}</button>
              </div>
            </div>
            {% else %}
            <div class="btn-toolbar mb-2 mb-md-0">
              <div class="btn-group mr-1">
                <button class="btn btn-sm btn-outline-secondary"><a href="{% url 'login'%}?next={{request.path}}">Login</a></button>
              </div>
              <div class="btn-group mr-1">
                <button class="btn btn-sm btn-outline-secondary"><a href="{% url 'websiteapp:signup'%}?next={{request.path}}">Signup</a></button>
              </div>
            </div>
            {% endif %}
          </div>
          {% block content %}
          {% endblock %}
        </main>
      </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

websiteapp/templates/device_detail.html
{% extends "base_generic.html" %} 

{% block main_page_title %}
    <strong>Monitoring: </strong>{{ device.get_title }}
{% endblock %}

{% block detail_monitoring %}
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
    <span>Saved reports</span>
    </h6>
    <ul class="nav flex-column mb-2">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'websiteapp:detail_device' device.get_uuid 'hour' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
        Last hour
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'websiteapp:detail_device' device.get_uuid 'day' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
        Last day
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'websiteapp:detail_device' device.get_uuid 'week' %}">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
        Last week
        </a>
    </li>
    <br>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'api:report-api' device.get_uuid %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bar-chart-2"><line x1="18" y1="20" x2="18" y2="10"></line><line x1="12" y1="20" x2="12" y2="4"></line><line x1="6" y1="20" x2="6" y2="14"></line></svg>
          API format
        </a>
      </li>
    </ul>
{% endblock %}

{% block content %} 
    {% if not failed %}
    {% load static %}
    <div class="row">
        <div class="col-md-9">
            <canvas id="myChart"></canvas>
        </div>
        <div class="col-md-3">
            <form class="card p-2">
                <div class="input-group">
                    <div class="input-group-append col-md-6">
                        <button type="submit" class="btn btn-primary btn-block my-breakwork">Turn on</button>
                    </div>
                    <div class="input-group-append col-md-6">
                        <button type="submit" class="btn btn-secondary btn-block my-breakwork">Turn off</button>
                    </div>
                </div>
                </form>
            <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <span class="text-mute my-breakwork">Title</span>
                </div>
                <span class="text-muted my-breakwork">{{ device.get_title }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <span class="text-mute my-breakwork">Measurement</span>
                </div>
                <span class="text-muted my-breakwork">{{ device.get_quantity }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <span class="text-mute my-breakwork">Serial number</span>
                </div>
                <span class="text-muted my-breakwork">{{ device.get_serial_number }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <span class="text-mute my-breakwork">Border value</span>
                </div>
                <span class="text-muted my-breakwork">{{ device.get_border_value }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                <span class="text-mute my-breakwork">Period of time</span>
                </div>
                <span class="text-muted my-breakwork">{{ timeperiod }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
                <span class="my-breakwork">Total number of measurements: </span>
                <strong class="my-breakwork">{{ total_measures }}</strong>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
                <div>
                    <span style="font-size: 13px" class="text-mute my-breakwork text-success">{{ device.get_uuid }} </span>
                </div>
            </li>
            </ul>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.js"></script>
    <script src="{% static 'js/chart.js' %}"></script>

    <script>
        var ctx = document.getElementById('myChart');
        var times = JSON.parse('{{ times | safe }}');
        var values = JSON.parse('{{ values | safe}}');
        getchart("MYDEVICE", "myChart", times, values, '{{ device.get_quantity }}')
    </script>
    {% endif %}
{% endblock %}

websiteapp/templates/integration.html
{% extends "base_generic.html" %}

{% block main_page_title %}
    Integration
{% endblock %}

{% block content %}
    {% load static %}
    <div class="badge text-wrap">
        <h3 class="font-weight-bold">This remote monitoring system requires the following components:</h3>
        <ol class="list-counter-circle">
          <li>Devices with a data channel to the local server</li>
          <li>Script on the local server that serializes data received from the device</li>
          <li>Connecting a local server to the Internet</li>
        </ol>
        <br>
        <p class="font-weight-bold">In our case, the MQTT protocol is used to transfer data from the device to the local server, but this is not important there, because all work with entering measurements into the database occurs using api</p>
        <br>

        <h3>How to start?</h3>
        <ul class="list-rectangle">
            <li>Sign up</li>
            <li>Add a controlled device on the page <a href="{% url 'websiteapp:list_devices' %}">"Devices"</a>(link)</li>
            <li>Get device UUID on the detailed device page</li>
            <li>Get user token on this page or from api (see next)</li>
            <li>Use API to collect measurements</li>
            <li>Monitor devices on the page "Devices" (charts and turn on-off Feedback)</li>
        </ul>
    </div>
    <div class="text-wrap"> 
        <h3>API Input Points</h3>
        <blockquote class="blockquote-reverse">
            <p><b>/api/users</b></p>
            <footer class="font-italic">
            {
                "username": "xxx", 
                "email": "xxx",
                "password": "xxx"
            } 
            </footer>
        </blockquote>
        <blockquote class="blockquote-reverse">
            <p><b>/api/login</b></p>
            <footer class="font-italic">
            {
                "username": "xxx", 
                "password": "xxx"
            }
            </footer>
        </blockquote>
        <blockquote class="blockquote-reverse">
            <p><b>/api/report/UUID/</b></p>
            <footer class="font-italic">        
            {
                "token" : "xxx",
                "data" : {
                    "time": "xxx",
                    "value": "xxx"
                }
            }
            </footer>
        </blockquote>
    </div>
    <br>
    <br>
    <div class="text-wrap">
        {% if user.is_authenticated %}
            <p class="font-weight-bold">Your user token is: {{ token }} </p>
        {% endif %}
    </div>



    </div>
    
{% endblock %}

websiteapp/templates/list_devices.html
{% extends "base_generic.html" %}

{% block main_page_title %}
    Devices
{% endblock %}

{% block content %}
{% load static %}

<div class="container">
    <div class="row row-conformity row-centered">
        <div class="col-xs-12 col-lg-4 my-auto">
            <div class="jumbotron text-center my-auto ">
                <h1>Add new device!</h1>
                <p class="lead">Add your device and monitor the status online!</p>
                <p><a class="btn btn-lg btn-success" href="{% url 'websiteapp:add_device_form' %}" role="button">Get started</a></p>
            </div>
        </div>
        {% for device in device_list %}
        <div class="col-xs-12 col-lg-4 my-auto">
                <div class="card-header text-center">
                    <h4 class="my-0 font-weight-normal">{{ device.title }}</h4>
                </div>
                <div class="card-body text-center">
                    <img class="img-fluid img-circle" src="{% static 'img/plus.png' %}">
                    <ul class="list-unstyled mt-3 mb-4">
                        <li><b>Serial Number:</b> {{device.serial_number}} </li>
                        <li><b>Measurements:</b> {{device.quantity}} </li>
                    </ul>
                    <a href="{{ device.get_absolute_url }}" class="btn btn-success stretched-link">More details</a>
                </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

websiteapp/templates/signup.html
{% extends "base_generic.html" %}
{% block main_page_title %}
    Signup
{% endblock %}
{% block content %}
  <h2>Sign up Form</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}